### ISSUE TITLE
My game crashed before it could even start :/

### ISSUE THREAD

**Issue by honestlyitssam** [TheCyberBrick/The-Betweenlands#998] opened 2020-03-11 06:34 UTC
Sorry. this is the first time I've done anything like this, usually my brother tells me what's wrong/how to fix it, but he's at college now so I'm lost :/

#### Betweenlands version: 
3.5.7

#### Forge version:
14.23.5.2838

#### Installed mods:
https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons

#### Link to full crash log
https://paste.dimdev.org/yayurabige.mccrash

#### How to reproduce:
I tried to start the game up from a modpack on twitch. And it didn't work like three times so :/

Step 1: Attempt to start game from the modpack using twitch desktop app

#### Expected result:
I expected my game to start

#### Actual result:
It... didn't

#### Pictures:
I attached the picture because I didn't know how to make it a link, sorry!
![crash](https://user-images.githubusercontent.com/62048359/76388704-efb8e380-6326-11ea-838f-37ccc80f33fa.PNG)

Sorry. this is the first time I've done anything like this, usually my brother tells me what's wrong/how to fix it, but he's at college now so I'm lost :/

**Comment by TheCyberBrick** [comment] 2020-03-11 16:31
Duplicate of #995, will discuss it there.

**Closed as completed by TheCyberBrick** 2020-03-11 16:31 UTC
