### ISSUE TITLE
Shaders don't turn off

### ISSUE THREAD

**Issue by HeberonYT** [TheCyberBrick/The-Betweenlands#923] opened 2019-11-12 19:42 UTC
#### Betweenlands version:
TheBetweenlands-3.5.1-universal.jar

#### Forge version:
1.12.2-forge1.12.2-14.23.5.2838

#### Singleplayer or Multiplayer:
Singleplayer and Multiplayer

#### Installed mods:
OptiFine_1.12.2_HD_U_E3.jar

## Description of the problem
I am using version 3.5.1 and I have disabled Betwenlands shaders, but for some strange reason it still causes visual problems in the overworld when I use Sildurs Vibrant Shaders v1.17 Extreme.

`rendering {
    I:"Sky texture resolution (only when shaders are enabled)"=512
    B:"Use shaders for rendering (this forces FBOs to be enabled)"=false

    # Whether the shaders should only be active in the Betweenlands dimension (if they are enabled)
    B:dimension_shader_only=true

    # Some blocks glow in the dark (eg Life Crystal Ore) which doesn't work in some cases. If you run into problems like broken textures for such blocks then set this to false
    B:fullbright_blocks=false

    # Shader rendering priority. Some other mods are not compatible with Betweenlands shaders (e.g. LadyLib/Dissolution) due to order conflicts. If you run into such an incompatibility try using a different priority. However rendering the shader earlier may introduce other rendering artifacts so this should be left as default if there are no conflicts.
    # 0: Late (Default)
    # 1: Normal
    # 2: Early
    # Min: 0
    # Max: 2
    I:shader_priority=0

    # Whether clouds should be rendered in sky rifts
    B:sky_rift_clouds=true

    # Only works when shaders are enabled. Determines the resolution of the shader sky texture. Bigger resolutions may have a bad impact on performance
    # Min: 16
    # Max: 2147483647
    I:sky_texture_resolution=512

    # Some features in the Betweenlands use shaders for special effects. If you don't have a dedicated graphics card or want to use other mods with shaders you should set this to false. May have an impact on performance depending on your computer. Forces FBOs to be enabled
    B:use_shader=false

    # Min: 0
    # Max: 100
    I:wisp_quality=50
}`

#### Pictures:
![2019-11-12_13 38 56](https://user-images.githubusercontent.com/13698597/68704486-fdfe1b00-0551-11ea-9255-9248e45978ed.png)
![2019-11-12_13 39 25](https://user-images.githubusercontent.com/13698597/68704488-fe96b180-0551-11ea-941c-84654f5d55c4.png)

**Comment by cheshyrp** [comment] 2019-11-13 01:34
Same with me, though it wasn't quite as extreme. Downgrading to Betweenlands 3.4 fixes the issue for the moment.

**Comment by theishiopian** [comment] 2019-11-13 22:56
A friend of mine has this issue as well, can confirm.

**Comment by TheCyberBrick** [comment] 2019-11-14 13:01
Closing as duplicate of #922

**Closed as completed by TheCyberBrick** 2019-11-14 13:01 UTC
