### ISSUE TITLE
Incompatibility with Grimpack, crash causes when an item is searched on JEI

### ISSUE THREAD

**Issue by BugmanBugman** [TheCyberBrick/The-Betweenlands#759] opened 2018-11-04 03:56 UTC
#### Betweenlands version:
The Betweenlands v3.4.0

#### Forge version:
1.12.2 - 14.23.5.2772

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
https://hastebin.com/izafawedoc.rb
+ Millenaire

## Link to full crash log
https://paste.dimdev.org/meliwibaxo.mccrash

#### How to reproduce:

1. Install Grimpack and Betweenlands
2. Search up the fence item from Grimpack in JEI
3. Game should crash

#### Expected result:
For the fence item to show up on JEI

#### Actual result:
Game crashes

**Comment by GoryMoon** [comment] 2018-11-04 11:52
Duplicate of #749, it's fixed and will be available in 3.4.1

**Closed as completed by GoryMoon** 2018-11-04 11:52 UTC
