### ISSUE TITLE
Portal Tree Desyncing/Spamming

### ISSUE THREAD

**Issue by Divineaspect** [TheCyberBrick/The-Betweenlands#379] opened 2017-03-19 05:20 UTC
We're getting, on a server, a lot of portal trees, just from going through the same tree on the betweenlands side.

**Comment by TheCyberBrick** [comment] 2017-03-19 10:55
What version are you using?

**Comment by Divineaspect** [comment] 2017-03-19 18:57
2.0.2 alpha universal

**Comment by TheCyberBrick** [comment] 2017-03-20 15:43
What server type are you using? Are you by any chance using Sponge? Somebody else on the forums has a similar problem which is likely caused by some incompatibility with Sponge/SpongeForge.

**Comment by Divineaspect** [comment] 2017-03-20 18:32
Nope. we're running forge. Test server for WLR, so it's a pretty heavy pack.

**Comment by TheCyberBrick** [comment] 2017-03-20 18:35
Please try without the other mods. Also, what's WLR?
@Divineaspect and please be a bit more specific, you're not giving me much information to work with. What other mods are installed?

**Comment by Divineaspect** [comment] 2017-03-20 18:46
Wanderlust Renewed.

We won't be testing it without other mods on the server, the server is for testing play-through mod compatibility.

**Comment by TheCyberBrick** [comment] 2017-03-20 18:49
Well, I can't really help then.

**Comment by Divineaspect** [comment] 2017-03-20 19:12
Ok, in a quick MMC instance with nothing but last 1.10, and lastest forge and betweenlands. Create portal tree, die in betweenlands, reenter portal tree.

http://imgur.com/mGjCkiZ

This was easy to reproduce.

**Comment by TheCyberBrick** [comment] 2017-03-20 19:23
> This was easy to reproduce.

You say, yet I can't reproduce it myself, nor did anybody else report this yet.
I'll try it with MultiMC and see if that's the cause.
Could you also tell me which OS you are using? There _might_ be something wrong with the file paths.

**Comment by Divineaspect** [comment] 2017-03-20 19:27
I'm using Windows 8, the server is using either unix or linux

**Comment by belathus** [comment] 2017-03-20 19:43
Server owner here. Server doesn't use MultiMC, as it is headless. It is running Debian Linux. We have 12 portals around our spawn area last I checked thanks to this bug.

**Comment by TheCyberBrick** [comment] 2017-03-20 19:49
I see. This might take a while as I don't have much time right now and I can't reproduce it.

**Comment by Captainaviator** [comment] 2017-03-21 02:34
We're seeing the same issue on our server.  2.0.2-alpha-universal.  We're using a Curse Modpack.

**Comment by An-Sar** [comment] 2017-03-24 06:45
The plot thickens, I tested a new world with just Between and then with our full pack. In each case there was no problem, however when switching back to our existing world I immediately got a new tree when returning to the overworld.

I tried creating a new world without between and then adding it in after initial chunks had generated, since between was added quite awhile after our world was started, but this still did not recreate the issue.

Another kind of weird bit is that all the duplicate trees on the overworld side generate near each other, but **Not near the original tree** used to enter the betweenlands.  Duplicate trees on the other side appear to be all clustered together.

Betweenlands: 2.0.2-alpha
Forge: 1.10.2-12.18.3.2254
Server platform is FreeBSD using OpenJDK 8.121.13

**Comment by TheCyberBrick** [comment] 2017-03-24 09:19
> Another kind of weird bit is that all the duplicate trees on the overworld side generate near each other, but Not near the original tree used to enter the betweenlands. Duplicate trees on the other side appear to be all clustered together.

The BL portals work quite differently from the standard/vanilla portals. In the BL dimension they look for the nearest Swamplands/Patchy Islands biome to generate in which can sometimes offset the portal on the other side by quite a lot. This is necessary though so that you don't have to start out in a harsh Sludge Plains biome or similar.
Once both portals are generated they are linked and that data is stored in the chunks' NBT.
I'm assuming that chunk data is somehow lost and then causes this bug since the portals are then no longer linked and generate a new portal on the other side.
I am currently rewriting some of that code using Forge's capabilities which should hopefully fix this bug. It might take a while until I get to finish that though.

**Comment by TheCyberBrick** [comment] 2017-03-24 09:34
Could one of you spawn in the 'thebetweenlands:location_debug' item and check if there is a coloured box around the broken portals?  If no box shows up around the portal then the link was lost. If it does show up, put the item in your main hand and right click on the portal block you used and something along the lines of "Marked ... locations as dirty and queued..." should show up in the chat and then check if that fixed the portal.

**Comment by An-Sar** [comment] 2017-03-24 19:19
Ok, so the original tree has a box and has 0 locations marked dirty, however when I travel to betweenlands, lots of trees have boxes and they are all marked dirty from what I could see.

Returning to the overworld makes a new tree with a box which is again marked dirty for all locations I clicked on.

I took some pictures,
https://i.imgur.com/TIpu29n.png
https://i.imgur.com/BqjWf93.png
https://i.imgur.com/BJfaV20.png

Thanks

**Comment by TheCyberBrick** [comment] 2017-03-24 19:45
Ah thanks. Seems like it is indeed caused by the data being lost somehow

**Comment by An-Sar** [comment] 2017-03-24 20:13
We've had some other weird issues with TEs appearing to loose data when chunks unload, such as IC2 cables and EnderIO item conduits, chunk loading fixes those cases so I tried chunk loading the original tree that doesn't show any dirty locations but it didn't seem to have any effect. Arriving on the other side the new tree immediately showed lost data.

Let me know if you want me to try anything else.

thanks

**Comment by TheCyberBrick** [comment] 2017-04-08 21:26
@pau101 I'm not sure if this is caused by the same bug, if what @An-Sar said is correct it's caused by the link data being lost. This _could_ have been fixed with #379, but I'm not sure if this here is the same problem

**Comment by pau101** [comment] 2017-04-08 21:33
@TheCyberBrick I'm not completely certain, but I think it is likely. @An-Sar Can you try this [experimental version](http://www.mediafire.com/file/j73ouzu6fdi9dzk/TheBetweenlands-2.0.3-alpha-universal.jar) and check if it stops new trees from generating?

**Comment by TheCyberBrick** [comment] 2017-04-08 22:06
@pau101 that could be the case. But if @An-Sar is right and it said "0 locations marked dirty" when right clicking on a portal with the Location Debug Item then that means the link in that chunk was lost. By the way, have you been able to reproduce this problem? I've tried many times but was unable to

**Comment by pau101** [comment] 2017-04-09 00:31
@TheCyberBrick I couldn't reproduce the issue using the two accounts I have.

**Comment by An-Sar** [comment] 2017-04-09 08:36
It looks like this did fix the issue. The original tree still sent me to a new tree, but after that the portals worked as expected going both directions. I destroyed and replaced the original tree and the replacement tree is behaving properly as well.

Thanks!

**Comment by pau101** [comment] 2017-04-09 18:28
Great news! The official release should be soon.

**Closed as completed** 2017-12-16 16:47 UTC
Labels: Bug, Resolved
