### ISSUE TITLE
Caught exception from The Betweenlands

### ISSUE THREAD

**Issue by FrostCreeper07** [TheCyberBrick/The-Betweenlands#784] opened 2019-01-29 01:59 UTC
#### Betweenlands version:
Version 3.4.3

#### Forge version:
Forge 14.23.5.2808

#### Singleplayer or Multiplayer:
During Game Load

#### Installed mods:
https://pastebin.com/Qqgm7HMj 
Pasted from crashlog so ignore the other info then the mod names

## Link to full crash log
https://pastebin.com/XFN0iPFp

#### How to reproduce:

1.Start Up Minecraft
2.Forge Loads
3. Crashes with This Error

**Comment by GoryMoon** [comment] 2019-01-29 08:15
Duplicate of #772

**Closed as completed** 2019-01-29 08:15 UTC
Labels: Incompatibility, Duplicate
