### ISSUE TITLE
Crash during init.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [TheCyberBrick/The-Betweenlands#349] opened 2017-03-03 07:32 UTC
Can't start the game. Crashes after a few seconds in init screen https://hastebin.com/coxuhivazo.sql

**Comment by theishiopian** [comment] 2017-03-03 07:49
Just for clarification, did this happen as soon as you tried to install the betweenlands?

**Comment by TheCyberBrick** [comment] 2017-03-03 08:37
Can you verify that this is only caused by the BL only and not another mod? Try with the BL only and then gradually add more mods to find out which mod(s) are causing this.

**Comment by Unrepentant-Atheist** [comment] 2017-03-03 20:02
@theishiopian No, during initialization. When the game was loading all the mods...

**Comment by theishiopian** [comment] 2017-03-03 20:20
That's not what I meant. I meant, did it happen right after you installed the bl? As in, the first time you loaded it after the bl was installed.

**Comment by TheCyberBrick** [comment] 2017-03-03 20:34
I'll close this because it's the same as #350

**Closed as completed by TheCyberBrick** 2017-03-03 20:34 UTC
