### ISSUE TITLE
Client crash on right-clicking any Block in JEI

### ISSUE THREAD

**Issue by Bulldog83** [TheCyberBrick/The-Betweenlands#659] opened 2018-07-05 06:55 UTC
## Versions
**Minecraft:** 1.12.2
**Forge:** 14.23.4.2705
**The Betweenlands:** 3.3.10
**EnderIO:** 5.0.29
**JEI:** 4.11.0.204
Uses dedicated forge-server w/o sponge.

#### Installed mods:
https://gist.github.com/Bulldog83/82bab025e93f562dfba0608c71a2feb2

## Link to full crash log
https://gist.github.com/Bulldog83/b5349e25359fa1e7da356111ddb9b87b

## Description of the problem
Game crashes on the client-side when I try to right-click on any Block in JEI with The Betweenlands installed.

**Comment by Jizanthapus** [comment] 2018-07-10 18:25
Possible duplicate of #663

**Comment by Bulldog83** [comment] 2018-07-10 18:57
Yes, this is the same.

**Closed as completed** 2018-07-10 19:21 UTC
Labels: Duplicate

**Comment by Bulldog83** [comment] 2018-07-10 19:30
Actually, #663 is duplicate of mine issue. :)

**Comment by pau101** [comment] 2018-07-10 21:04
Yep, marked this a dupe since the other is where my responses are at. This one was just overlooked.
