### ISSUE TITLE
Crash at Launch with voidcraft and betweenlands installed

### ISSUE THREAD

**Issue by artisticmathematician** [TheCyberBrick/The-Betweenlands#351] opened 2017-03-03 20:57 UTC
Hello there,

I was trying to ad this mod to my 1.10.2 server and it seems to work well with all my mods except voidcraft. When I have voidcraft installed, the game crashes upon initialization. If I remove either this mod or voidcraft, the game launches without any issues. 

https://mods.curse.com/mc-mods/minecraft/251730-voidcraft#t1:description

Here is the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.0-alpha-universal.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/3/17 12:36 PM
Description: Initializing game

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:35)
	at net.minecraftforge.client.model.ModelLoader.onPostBakeEvent(ModelLoader.java:1042)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:401)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:35)
	at net.minecraftforge.client.model.ModelLoader.onPostBakeEvent(ModelLoader.java:1042)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:401)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 233129088 bytes (222 MB) / 1261699072 bytes (1203 MB) up to 7422279680 bytes (7078 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -Xmn896M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 Optifine OptiFine_1.10.2_HD_U_D6 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221.jar) 
	UCH	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	aether_legacy{v1.3.1-1.10.2} [Aether Legacy] (aether_legacy-1.3.1.jar) 
	UCH	BiomesOPlenty{5.0.0.2155} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar) 
	UCH	cavern{1.5.5} [Cavern] (Cavern_1.10.2-v1.5.5.jar) 
	UCH	chunkgen{1.3} [ChunkGen] (chunkgen-1.10.2-1.5.0.jar) 
	UCH	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
	UCH	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCH	JEI{3.14.5.406} [Just Enough Items] (jei_1.10.2-3.14.5.406.jar) 
	UCH	MineTweaker3{3.0.20} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCH	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCH	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod-10.0.6.jar) 
	UCH	hempfarmer{1.7.4} [HempFarmer] (hempfarmer-1.10.2-1.7.4.jar) 
	UCH	ironbackpacks{1.10.2-2.2.22} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.22.jar) 
	UCH	journeymap{1.10.2-5.4.4} [JourneyMap] (journeymap-1.10.2-5.4.4 (1).jar) 
	UCH	mazemod{1.4.0} [The Maze World Mod] (mazemod-1.4.0.jar) 
	UCH	mtrm{1.2.1.20} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.20.jar) 
	UCH	mod_autofish{1.10-1.2} [AutoFish Forge Mod] (mod_autofish_forge-1.10-1.2.jar) 
	UCH	xreliquary{1.10.2-1.3.3.639} [Reliquary] (Reliquary-1.10.2-1.3.3.639.jar) 
	UCH	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCH	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UCH	spawnercraft{3.1} [SpawnerCraft] (SpawnerCraft 1.10.2-3.3.1.jar) 
	UCH	switchbow{1.0.1} [Switch-Bow] (switchbow-1.0.1.jar) 
	UCH	tails{1.10.2-1.8.3} [Tails] (Tails-1.10.2-1.8.3.jar) 
	UCH	tammodized{0.6.2} [TamModized] (TamModized-1.10.2-0.6.2.jar) 
	UCH	terrainCrystals{1.2.3} [Terrain Crystals] (Terrain Crystals 1.10.2 - 1.2.3.jar) 
	UCH	terrainCrystalsAddons{1.1.1} [Terrain Crystals Addons] (TC Addons 1.10.2-1.1.1.jar) 
	UCH	teletoro{1.10.2-20} [TeleToro] (teletoro-1.10.2-20.jar) 
	UCH	thebetweenlands{2.0.0-alpha} [The Betweenlands] (TheBetweenlands-2.0.0-alpha-universal.jar) 
	UCH	utilityworlds{1.1.0} [Utility Worlds] (UtilityWorlds-1.10.2_1.1.0.jar) 
	UCH	voidcraft{0.15.1} [VoidCraft] (VoidCraft-1.10.2-0.15.1.jar) 
	UCH	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.3.1.2.jar) 
	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.0-alpha-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14008 Compatibility Profile Context 21.19.137.514' Renderer: 'Radeon (TM) RX 470 Graphics'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2221
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 470 Graphics GL version 4.5.14008 Compatibility Profile Context 21.19.137.514, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8120 Eight-Core Processor 
	OptiFine Version: OptiFine_1.10.2_HD_U_D6
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.14008 Compatibility Profile Context 21.19.137.514
	OpenGlRenderer: Radeon (TM) RX 470 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

I love this mod, I am still running it (without voidcraft), and it is AMAZING! Thank you for updating to 1.10.2 <3

**Comment by TheCyberBrick** [comment] 2017-03-03 21:06
Duplicate of #350

**Closed as completed by TheCyberBrick** 2017-03-03 21:06 UTC

**Comment by TheCyberBrick** [comment] 2017-03-03 22:01
> I love this mod, I am still running it (without voidcraft), and it is AMAZING! Thank you for updating to 1.10.2 <3

Oh, and thanks! :)
