### ISSUE TITLE
[1.12.2] Crash on Load

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#754] opened 2018-11-01 21:51 UTC
#### Betweenlands version:
3.4.0

#### Forge version:
2768

#### Singleplayer or Multiplayer:
SP

#### Installed mods:
https://pastebin.com/wubsDrnJ

## Link to full crash log
https://pastebin.com/MWF7YqyB

## Description of the problem
Crash loading game.

**Comment by MokahTGS** [comment] 2018-11-01 22:03
Rolled back a version and no crash.

**Comment by GoryMoon** [comment] 2018-11-01 22:20
Duplicate of #737. This was already reported to Project Red

**Closed as completed** 2018-11-01 22:21 UTC
