### ISSUE TITLE
crash on start up

### ISSUE THREAD

**Issue by TheNimbleNinja** [TheCyberBrick/The-Betweenlands#746] opened 2018-10-28 02:03 UTC
#### Betweenlands version:
the betweenlands v3.4.0

#### Forge version:
forge 14.23.5.2770

#### Singleplayer or Multiplayer:
before the game loads

#### Installed mods:
https://gist.github.com/TheNimbleNinja/0db746633c1e5d6b032a408ae17809ff

## Link to full crash log
https://gist.github.com/TheNimbleNinja/f9d84acd8c05c65d6cc3bd326075f916

#### How to reproduce:
on game loading it crashes

**Comment by TheCyberBrick** [comment] 2018-10-28 09:33
Duplicate of #737. This was already reported to Project Red

**Closed as completed by TheCyberBrick** 2018-10-28 09:33 UTC
