### ISSUE TITLE
Startup Crash With ProjectRed

### ISSUE THREAD

**Issue by AxolotlAccount** [TheCyberBrick/The-Betweenlands#772] opened 2018-11-22 04:03 UTC
#### Betweenlands version:
3.4.1 (Minecraft 1.12.2)

#### Forge version:
Forge 14.23.5.2775

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Crash Log has list of all mods.

## Link to full crash log
https://paste.dimdev.org/netajoyudi.mccrash

#### How to reproduce:
Start the game again.

#### Expected result:
Game should be opened.

#### Actual result:
Crash On Startup

#### Pictures:
No picture.

**Comment by theishiopian** [comment] 2018-11-22 05:53
Looks like a duplicate of #737 to me. Stacktraces are almost identical.

**Comment by TheCyberBrick** [comment] 2018-11-22 11:10
Yes, this is a project red bug.

**Comment by GoryMoon** [comment] 2018-12-29 10:25
Gonna link this as temp fix for users wanting to use PR relocation stuff until it's updated
https://github.com/MrTJP/ProjectRed/issues/1429

**Comment by warplord** [comment] 2019-01-05 14:12
What is the temporary fix and will it be updated to fix the crash soon?

**Comment by GoryMoon** [comment] 2019-01-05 19:50
The tmp fix is to `downgrade ProjectRed to 4.9.0.086` or not use the relocation part of project red

**Comment by O13SC3N3** [comment] 2019-01-14 01:48
So what were the changes on TBL side to cause the side of the crash as well? Some are even saying downgrading TBL fixes the issue... 3.3.13 works.

**Comment by GoryMoon** [comment] 2019-01-14 02:08
Moving from an old deprecated way of registering tileentities for rendering as items.

**Comment by AxolotlAccount** [comment] 2019-01-14 02:13
I downloaded Project Red version 1.12.2-4.9.2.110 and the problem fixed.

**Comment by GoryMoon** [comment] 2019-01-14 02:27
It's been fixed on ProjectReds side since mid July 2018 but not released publically yet.

**Comment by O13SC3N3** [comment] 2019-01-16 11:11
> I downloaded Project Red version 1.12.2-4.9.2.110 and the problem fixed.

Where is that version located?

**Comment by KuroNeko87** [comment] 2019-01-22 05:01
http://chickenbones.net/maven/mrtjp/ProjectRed/1.12.2-4.9.2.110/

**Comment by O13SC3N3** [comment] 2019-01-23 03:00
> http://chickenbones.net/maven/mrtjp/ProjectRed/1.12.2-4.9.2.110/

Cool, thank you! Project Red All, all the modules even compat etc?

**Comment by SirTwsted** [comment] 2019-02-26 20:39
I just wanted to point out that Today February 26th 2019th
This crash still happens when using ProjectRed-1.12.2-4.9.1.92  and The Betweenlands v3.4.4
When you actually use a lower version of The Betweenlands such as the one im using now v3.3.13
All works well and no crashes happen.
The crash actually happens when updating The Betweenlands mod to v3.4.4
Just wanted to point this out to everyone and specially the Developers

**Comment by GoryMoon** [comment] 2019-02-26 20:49
As noted above it's fixed on PRs side but not officially released (the fix was about 8 months ago), the newer versions can be found on the maven above.

**Comment by SirTwsted** [comment] 2019-02-26 23:02
ok thank you.  :)

**Comment by barcharcraz** [comment] 2019-06-24 01:32
I still get the crash with the lastest versions of PR from maven?

edit: I'm an idiot, use the seperate mod jars for PR and not -all.

**Comment by GoryMoon** [comment] 2019-07-10 11:12
There has been an official release of the fix for this, if you have this issue download v4.9.3+ of ProjectRed.

**Closed as completed** 2019-11-15 17:41 UTC
Labels: Incompatibility, Resolved
