### ISSUE TITLE
The game crashes with FTB Revelation modpack

### ISSUE THREAD

**Issue by sersimovi** [TheCyberBrick/The-Betweenlands#771] opened 2018-11-21 19:05 UTC
#### Betweenlands version:
v3.4.1

#### Forge version:
forge-14.23.5.2768

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
FTB Revelation Modpack v2.0.6

Mod | Authors
-- | --
/dank/null | TheRealp455w0rd
Actually Additions | Ellpeck
Actually Baubles | Jacky1356400
Akashic Tome | Vazkii
AppleSkin | squeek502
Applied Energistics 2 | AlgorithmX2
ArchitectureCraft | darkevilmac
Aroma1997Core | Aroma1997
Aroma1997's Dimensional World | Aroma1997
Astral Sorcery | HellFirePvP
AutoRegLib | Vazkii
B.A.S.E | lanse505
Bad Wither No Cookie - Reloaded | kreezxil
Baubles | azanor
BdLib | bdew
Bed Patch | Mordenkainen3141
Better Advancements | Way2muchnoise
Better Builder's Wands | Portablejim
BiblioCraft | JDSinclair
Binnie's Mods | Binnie567
Blockcraftery | elucent
Blood Magic | WayOfTime
Bookshelf | darkh4x
Botania | Vazkii
Brandon's Core | brandon3055
Career Bees | RWTema
Chameleon | jaquadro
Chest Transporter | CubeX2
Chisel | tterrag1098
Chisels & Bits | AlgorithmX2
Clumps | jaredlll08
CoFH Core | TeamCoFH
CoFH World | TeamCoFH
CodeChickenLib | covers1624
Compact Machines | Davenonymous
Compact Solars | progwml6
Compacter | bdew
ConnectedTexturesMod | tterrag1098
Construct's Armory | TheIllusiveC4
Controlling | jaredlll08
Cooking for Blockheads | BlayTheNinth
CraftTweaker | jaredlll08
Custom Main Menu | lumien231
Dark Utilities | darkh4x
Deep Resonance | McJty
Default Options | BlayTheNinth
Diet Hoppers | RWTema
Dirt2Path | marwat208
Draconic Evolution | brandon3055
ET Lunar | ValkyrieofNight
ElecCore | Elec332
EluLib | elucent
Embers | elucent
EnderCore | tterrag1098
EnderIO | CrazyPants
Ender Storage | covers1624
Engineer's Doors | Nihiltres
Engineers Workshop Reborn | modmuss50
Environmental Tech | ValkyrieofNight
Exchangers | Jacky1356400
Extra Rails | shadowfactsmc
Extra Utilities 2 | RWTema
ExtraCells2 | Destroyer7128
Extreme Reactors | ZeroNoRyouki
FTB Utilities | FTB
FTBLib | FTB
FastWorkbench | Shadows_Of_Fire
Fence Jumper | TheRealp455w0rd
Flat Colored Blocks | AlgorithmX2
Flux Networks | Ollie_Lansdell
Forestry | SirSengir
Gadgetry: Core | elucent
Gadgetry: Machines | elucent
Gendustry | bdew
Guide-API | TehNut
Immersive Engineering | BluSunrize
Immersive Petroleum | Flaxbeard
IndustrialCraft 2 | Player
Industrial Foregoing | Buuz135
Industrial Wires | malte0811
Initial Inventory | jaredlll08
Inventory Tweaks | Kobata
Iron Backpacks | gr8pefish
Iron Chests | progwml6
JEI Bees | bdew
JEI Integration | SnowShock35
JourneyMap | techbrew
Just Enough HarvestCraft | mrAppleXZ
Just Enough Items | mezz
Just Enough Resources | Way2muchnoise
KleeSlabs | BlayTheNinth
Long Fall Boots | NanoHeart
MCMultiPart | amadornes
MTLib | jaredlll08
Magic Bees | MysteriousAges
Mantle | mDiyo
McJtyLib | McJty
MineTogether | Creeperhost
Mod Name Tooltip | mezz
ModTweaker | jaredlll08
More Overlays | feldim2425
Morph-o-Tool | Vazkii
Morpheus | Quetzi
Mouse Tweaks | YaLTeR97
Natura | mDiyo
Nature's Compass | ChaosTheDude
NetherPortalFix | BlayTheNinth
Not Enough Wands | romelo333
NotEnoughIDs | fewizz
OpenBlocks | OpenMods Team
OpenModsLib | OpenMods Team
OpenComputers | SangarWasTaken
p455w0rd's Library | TheRealp455w0rd
Pam's HarvestCraft | MatrexsVigil
Placebo | Shadows_of_Fire
Platforms | ShetiPhian
Project Red | Mr_TJP
Quark | Vazkii
Quick Leaf Decay | lumien231
RFTools | McJty
RFTools Control | McJty
RFTools Power | McJty
Ranged Pumps | raoulvdberge
ReAuth | TechnicianLP
Reborn Core | modmuss50
Reborn Storage | modmuss50
Redstone Arsenal | TeamCoFH
Redstone Flux | TeamCoFH
Refined Storage | raoulvdberge
Refined Storage Addons | raoulvdberge
Reliquary | P3pp3rF1y
Resource Loader | lumien231
Roots | elucent
Rustic | mangoose3039
SecretRoomsMod | AbrarSyed
Shadowfacts' Forgelin | shadowfactsmc
ShetiPhianCore | ShetiPhian
Signals | MineMaarten
Simple Void World | modmuss50
Simply Jetpacks | Tomson124
Snad | TheRoBrit
Sonar Core | Ollie_Lansdell
Soot | BordListian
Soul Shards: The Old Ways | SgtPunishment
SplashAnimation | asiekierka
Steve's Carts Reborn | modmuss50
Storage Drawers | jaquadro
Storage Drawers Extras | jaquadro
TOP Addons | DrManganese
Tesla Core Lib | Face_of_Cat
Thaumcraft 6 | Azanor
Thaumic Inventory Scanning | BlayTheNinth
Thaumic JEI | Buuz135
The Lost Cities | McJty
The One Probe | McJty
The Twilight Forest | Benimatic
Thermal Cultivation | TeamCoFH
Thermal Dynamics | TeamCoFH
Thermal Expansion 5 | TeamCoFH
Thermal Foundation | TeamCoFH
Thermal Innovation | TeamCOFH
Thut's Elevators | patnevis
ThutCore | patnevis
Tinkers Construct | mDiyo
Tinkers' Tool Leveling | bonusboni
TipTheScales | jaredlll08
TorchMaster | xalcon
Translocators | covers1624
Traverse | ProfessorProspector
UniDict | WanionCane
ValkyrieLib | ValkyrieofNight
WanionLib | WanionCane
Waystones | BlayTheNinth
Wireless Crafting Terminal | TheRealp455w0rd
Woot | Ipsis
XNet | McJty
xNICEx | McJty
Xtones | TehNut
YABBA | LatvianModder
ZeroCore | ZeroNoRyouki

Spectrite v1.6.7
DrZhark's Mo'Creatures 12.0.5
OptiFine_1.12.2_HD_U_E2

## Link to full crash log
https://gist.github.com/sersimovi/28a9a159fc70cd04ae475bfb3e2e4e5b

#### How to reproduce:
I installed the FTB Revelation modpack using Twitch and then added a couple mods. The game crashes displaying an error message that says _'It looks like you're using an unsupported modified version of the game.'_ and then this:

 _'The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Betweenlands (thebetweenlands)'_

If I delete the betweenlands mod the game runs fine. What's causing this?

(I tried having the same mods working without twitch and still the same error.)

#### Pictures:
https://imgur.com/XHbNRlt

**Comment by GoryMoon** [comment] 2018-11-21 22:04
Duplicate of #737. 
This was already reported to Project Red and fixed on their side but not released yet.
More specifically it's the `Project Red - Mechanical` mod that's causing it.

**Closed as completed by GoryMoon** 2018-11-21 22:04 UTC
