### ISSUE TITLE
Crash with Project red

### ISSUE THREAD

**Issue by magcicada** [TheCyberBrick/The-Betweenlands#817] opened 2019-03-23 01:54 UTC
## Link to full crash log
[crash log](https://paste.dimdev.org/qozixobelo.mccrash)
#### Pictures:
This is the report of Vanilla Fix
![2019-03-23 093748](https://user-images.githubusercontent.com/45464670/54860171-5da07f80-4d51-11e9-8876-d018bb32f80a.png)

**Comment by WightofShadows** [comment] 2019-03-23 02:40
This is a duplicate of #772 - It's been fixed on Project Red's end for a long time, but a version with the fix hasn't been released yet. You can downgrade ProjectRed to 4.9.0.086 or use a dev version from the maven [repo](http://chickenbones.net/maven/mrtjp/ProjectRed/) in the meantime.

**Closed as completed by WightofShadows** 2019-03-23 02:40 UTC
