### ISSUE TITLE
Crash on startup (lot of mod)

### ISSUE THREAD

**Issue by MatiasuKun** [TheCyberBrick/The-Betweenlands#851] opened 2019-07-10 07:09 UTC
**Betweenlands version:**
3.4.9 (Minecraft 1.12.2)
and I tried 3.3.13

**Forge version:**
Forge 14.23.5.2838

On Singleplayer but i want to open a server next

**Installed mods:**
Crash Log has list of all mods.

**Link to full crash log**
_https://paste.dimdev.org/ivifobapuc.rb_

It crash on startup

**Comment by MatiasuKun** [comment] 2019-07-10 07:36
okay it's just that i've too much mod i'll try with NotEnoughIDs and JustEnoughIDs

**Comment by MatiasuKun** [comment] 2019-07-10 07:40
New crash report : https://paste.dimdev.org/wizaqufono.sql

**Comment by GoryMoon** [comment] 2019-07-10 11:11
Duplicate of #772 
This is fixed by an official release of ProjectRed, so you need to update that

**Closed as completed by GoryMoon** 2019-07-10 11:11 UTC
