### ISSUE TITLE
Thermal Expansion Reservoir client crash when attempting to pick up liquids

### ISSUE THREAD

**Issue by aking4125** [TheCyberBrick/The-Betweenlands#993] opened 2020-03-06 22:55 UTC
#### Betweenlands version:
TheBetweenlands-3.5.7

#### Forge version:
1.12.2 2847

#### Singleplayer or Multiplayer:
Multiplayer

#### Installed mods:
Can be viewed at the bottom of the crash log posted below.

## Link to full crash log
https://paste.dimdev.org/mofuliqovu.mccrash

#### How to reproduce:
They stated they tried to collect "Fog" in The Betweenlands. They were using the Thermal Expansion reservoir and attempted to pick up a fluid. Probably water or something, their not 100% certain. Once they used the reservoir, the client crashed for them with the report listed above. 

We'll be investigating this with proper steps on how to possibly reproduce it.

#### Expected result:
No crash and picked up a fluid from the Betweenlands?

#### Actual result:
Client crashes and continues to crash each time they log in. Teleported user back to the overworld and they are safe. They have returned to the Betweenlands via the portal and it hasn't crashed. They haven't returned to the spot where it occurs as of yet.

We understand that the crash mentions no fluid from reading it (Not that I can accurately decipher it anyways). But that is what the user on the server as informed me.

**Comment by TheCyberBrick** [comment] 2020-03-11 15:53
This may be caused by MoCreatures (https://github.com/Angry-Pixel/The-Betweenlands/issues/930)

**Comment by TheCyberBrick** [comment] 2020-04-02 11:33
There is now a new release with a potential fix for this. If it is still occurring then it is likely the incompatibility with MoCreatures.

**Closed as completed by TheCyberBrick** 2020-04-02 11:33 UTC
Labels: Bug?
