### ISSUE TITLE
Water disappears when you ride a Weedwood Rowboat and have Galacticraft installed

### ISSUE THREAD

**Issue by TheQKnight** [TheCyberBrick/The-Betweenlands#592] opened 2018-05-01 00:23 UTC
#### Betweenlands version:
Affects versions 3.3.1 - 3.3.8, Does not affect 3.0.0

#### Forge version:
MC 1.12.2 - Forge 2655

#### Singleplayer or Multiplayer:
Both

#### Installed mods:
Betweenlands 3.3.8
Galacticraft (all the 3 coremods)- Happens with all versions

#### How to reproduce:

1. Place Weedwood Rowboat in water
2. Ride in it
3. Water disappears

#### Expected result:
Water to not disappear

#### Actual result:
Water Disappears

#### Pictures:

![2018-04-30_11 54 53](https://user-images.githubusercontent.com/17223871/39456420-2831e45e-4c9b-11e8-8462-abcc15d42b73.png)

![2018-04-30_11 54 57](https://user-images.githubusercontent.com/17223871/39456421-2ca78d2c-4c9b-11e8-9def-45e6b7885a5a.png)

**Comment by radfast** [comment] 2018-05-01 00:35
Hi, Galacticraft dev here.  This is a duplicate of #568, please see my comments there.

**Closed as completed** 2018-05-01 15:20 UTC
Labels: Duplicate
