### ISSUE TITLE
Infuser Bugs

### ISSUE THREAD

**Issue by 63502** [TheCyberBrick/The-Betweenlands#650] opened 2018-06-25 18:40 UTC
#### Betweenlands version:
3.3.9

#### Forge version:
14.23.4.2712

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
[Mod List](https://gist.github.com/63502/7b374d06f78e6ca3855fef1d5d1f8520)

## Link to full crash log
N/A

## Description of the problem
Infusers have several issues when I try to used them.
1. They don't seem to progress at all when I add ingredients and stir them.
2. They don't auto-stir when stirred with a life crystal attached
3. They delete all contents and inserted life crystals when the closing and re-opening the world/game.
#### How to reproduce:

1. Use the infuser like it is intended to be used without a life crystal.
2. Place a life crystal on the infuser and attempt to activate it by stirring once
3. Exit to the menu while there are still ingredients/liquid/life crystals in the infuser.

#### Expected result:
Infusion Buckets can be retrieved with aspects and/or brews.

#### Actual result:
Lots of wasted time stirring an infuser that never showed any progress beyond boiling and "consuming" ingredients that were still visible in the basin (all 6 still floating in there, but I couldn't remove them). I left my world to do something else. When I came back to try again my infuser was empty and the life crystal was gone.

**Comment by WightofShadows** [comment] 2018-06-27 03:03
For a couple of your problems this could be caused by misinterpretation of how the Infuser works.

For Problem 1, were you using ingredients that were a valid Aspect combination for an Infusion? If not, the Infuser will not display any changes because it is not creating any of the specific Infusion recipes.
For Problem 2, you have to stir the Infuser manually at least once before the Life Crystal will function.

Some of the other things though, like losing items when relogging/being unable to remove items, sound like actual bugs.

**Comment by 63502** [comment] 2018-06-27 06:05
I am  well aware of how the life crystal stirring mechanics are supposed to work for the infuser, as I have used it successfully in previous versions. My concern was that I could not start the auto stir, even after stirring it once manually while a life crystal at full charge was attached to it.

From what I remember, the infuser contents are supposed change color slightly and dissolve the ingredients at some point as it is stirred, regardless of whether the aspect combination is valid or not. The special boiling animation with extra noise, steam, and drastic color change only happens when valid brews reach the completion point, and no excess aspects are left in the infuser. 

My intent when I discovered problem 1 was to collect the single aspect needed to craft marsh runner boots by dissolving 6 of a single type of ingredient, then distilling the contents for pure aspects.

**Comment by TheCyberBrick** [comment] 2018-06-28 15:11
The Life Crystal only stirs if the ingredients produce an elixir, pretty sure it has always been that way until now. However, I've changed that now so that it always automatically stirs as long as there are any ingredients in the water, regardless of whether they produce an elixir.
For combinations that don't produce an elixir it doesn't matter how long the ingredients have been boiled. You can fill your bucket with the infusion as soon as you've stirred it once. To make that a bit more obvious I've now added an animation just like when a valid combination finishes infusing.

**Comment by TheCyberBrick** [comment] 2018-06-28 15:12
The bug with contents being lost when reloading the world is now fixed, new update will be available soon.

**Closed as completed by TheCyberBrick** 2018-06-28 15:12 UTC
